project:
  type: website
  output-dir: docs
  
execute: 
  freeze: true

website:
  title: "luo"
  description: the personal website of luo
  site-url: https://luo965.github.io/
  repo-url: https://github.com/luo965.github.io/
  twitter-card: true
  open-graph: true
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - file: "achievements.qmd"
        text: Achievements
    right: 
      - icon: linkedin
        href: www.linkedin.com
      - icon: twitter
        href: www.twitter

format:
  html:
    theme: 
      light: Sketchy 
      dark: Superhero
    css: styles.css
    toc: true

editor: visual

